default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: openbag_development

test:
  <<: *default
  database: openbag_test

production:
  <<: *default
  database: openbag_production
  username: openbag
  password: <%= ENV['REWILD_DATABASE_PASSWORD'] %>
